name: AutoMobile Seeker Actions

on: 
  schedule:
    - cron: '* * * * *' # Runs every other minutes 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Execute py script
        run: python main.py

      - name: Git pull
        run: git fetch --all

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update data.md
        id: auto-commit-action

      - name: Send email
        uses: devellany/send-mail@v1.0.2
        with:
            host: smtp.google.com
            # Optional port (defaults to 465)
            port: 465
            account: ${{secrets.ACCOUNT}}
            password: ${{secrets.MAIL_PASSWORD}}
            sender: devellany
            from: ${{secrets.MAIL_ADDRESS}}
            to: dilan2012salinda@gmail.com
            subject: test
            body: test
            # Optional content type (defaults to text/plain)
            contentType: text/plain
            # Optional attachment files (JSON type. require property 'path')
            #attachments: '[{"path":"README.md"}]'
